# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tales from Prod
email: talesfromprod+site@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Richard Finlay Tweed's thoughts on Cloud Native Software, Kubernetes, Production and whatever else he's been tinkering with.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tales.fromprod.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  RichardoC
destination: docs

# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# So pages by default have a nice URL that's not going to change with category refinement.
permalink: /:year/:y_day/:title:output_ext

timezone: Europe/London

# Theme config
color_scheme: "dark"
search_enabled: true
heading_anchors: true
footer_content: "Copyright &copy; 2024 Richard Finlay Tweed. All rights reserved. All views expressed are my own"
