title = 'Tales from Prod'
baseURL = 'https://tales.fromprod.com/'

defaultContentLanguage = 'en'
languageCode = 'en-gb'

googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false
theme = 'docura'
